### ISSUE TITLE
As of June 1, the version header needs to be set

### ISSUE THREAD

**Issue by cjavdev** [mgmarlow/notion-sdk-ruby#4]
Per the docs here: https://developers.notion.com/reference/versioning

The version needs to be set. I'm getting this error:

```
Notion::NotionError (Notion-Version header failed validation: Notion-Version header should be defined, instead was `undefined`.):
```

When trying to create a page.

**Comment by mgmarlow** [comment]
Fixed in `v0.3.1`. Thanks!
